### ISSUE TITLE
ways to import endnote format references with marco

### ISSUE THREAD

**Issue by Fokatu** [lutz/AutoRefAddon#4]
Hi,
I am writting here is to ask you a question.  I am working on an addon to import references to citavi project. The references are obtained by searching a database. I can get the references in endnote format. Do you know how to import the references with C#? I know that there is an interactive method to import the references, but I want to import the references right after searching whith no mouse operation. 
Thanks！

**Comment by lutz** [comment]
@Fokatu To develop an addon you will find [here](https://github.com/lutz/CitaviProjects#i-want-develop-my-own-addon-how-can-i-find-material) information about material. A good way to learn it is to explore the public repository of citavi addons [here](https://github.com/Citavi/C6-Add-Ons-and-Online-Sources).

In your particular case, the question would be what you have already developed. Citavi addons are generally developed in C#. You develop against a specific form e.g. the `MainForm`. Most of Citavi's forms inherit from `ProjectShellForm` whereby each form has a `Project` type property that manages titles. There you can add new references.

The Addon **ImportPdfsAndCategorySystem** in the public repository and the call of the `Macro` class shows you exemplary how information can be added to the project.

**Comment by Fokatu** [comment]
@lutz ,thank you for your reply.  
I managed to get the references in endnote format as attached below. I can also add a reference to the opened project with C# code. 
What I want to do is to use the "ImportForm" provided by Citavi to load the references so that I can filter some of the references out. But I don't know the interfaces of the "ImportForm". Do you have any idea on this?

`%0 Journal Article
%A 李修林
%+ 丹东市中心医院介入手术室;
%T CT及三维重建影像在胫骨平台骨折诊断和分型中的应用分析
%J 中国冶金工业医学杂志
%D 2020
%V 37
%N 02
%K 胫骨平台骨折;检查方法;检出率;三维重建影像;骨折移位;三维重建技术;
%X <正>胫骨平台骨折常首选手术治疗,但成功的手术离不开术前的准确诊断与分型。近些年,CT三维重建技术得到很大的发展,在骨与关节损伤中显示出明显的优越性。本文探讨CT及三维重建影像在胫骨平台骨折诊断和分型中的应用价值,报告如下。1对象与方法1.1研究对象选择2017年3月～2019年3月我院收治的105
%P 243-244
%@ 1005-5495
%L 21-1340/R
%W CNKI`

**Comment by lutz** [comment]
@Fokatu Can you add a picture of the form?

In general the `CitaviAddOn` class has a property called _HostingForm_ of type `AddOnHostingForm` The Enum describe the "official" supported forms of citavi. If you want develop against other forms you must implement it self. The main problem of getting access you can use my extended class `CitaviAddOnEx<T>`. The library you will find [here](https://github.com/lutz/CitaviAddOnEx). With this library you get the same interface like the official addon class but with support of all forms inherited by the `FormBase` class. This is the base form of all citavi forms.

The rest you must implemented self. When you get no public access to controls or data you must use **Reflection**.

**Comment by Fokatu** [comment]
The ImportForm: Reference=>Import ... (Menu command)
The ImportDialogWizard: File=>Import ... (Menu command)

**Comment by lutz** [comment]
Okay these dialogs are not official supported. So you must implement the logic self. With my extended model (see post above) you can develop an addon which is loaded for these specific forms and the rest is try and error with public members of forms or private members via reflection.

**Comment by Fokatu** [comment]
Thank you very much!

I am new to C# and citavi addon develop.


I have another question： can I define multiple "CitaviAddOn<MainForm>" addons?
From my experiment, only one such addon works. Do I miss any configuration?

**Comment by lutz** [comment]
No problem.

Since Citavi 6 it is no longer possible to deliver more than one addon per class library. The engine loads only one addon per dll. 

With the extended model (see post above) it is possible to develop against the base class and then resolve the specific class in the called methods. This avoids the problem of having to use different class libraries against different dialogs.
